sysCode: CBS # 目前都是 CBS
useCase: #菜单显示
  - wohome
  - wosale
mixNetType: '8900' # 目标融合类型，调用aop融合成员预提交接口用到
xxProductId: '31000000' # 行销商品标识，同意向单中的产品标识
xxProductName: '智慧沃家组合套餐（商用）' # 前台显示商品详细描述的文字
cbProductId: '89017300' # 提交集团接口 cb/aop 的产品标识
allowFromProducts: #cbss融合可以转此融合
  - '90361012'
  - '90311214'
members: # 配置包括主虚拟号在内的各类成员
  - type: CP # 成员英文类别，行销专用
    netTypeCode: 'CP' # 虚拟成员
    min: 1
    max: 1
    bundleList: #新装纳入
      - bundleId: '31000000'
        bundleName: '智慧沃家组合套餐（商用）'
        allowAdd: 1 # 1：允许  0 ：不允许 融合成员纳入
        allowNew: 1 # 1：允许  0 ：不允许 融合成员新装
        products:
        -
          productId: '89017300'
          productMode: '00'
          packages: # 商品固定带的包元素组合
           - packageId: '51002268'
             elementId: '50000'
             elementType: S # D-资费 S-服务
           - packageId: '51018056'
             elementId: '7000000'
             elementType:  D # D-资费 S-服务 
           - packageId: '51018573'
             elementId: '7000100'
             elementType:  D # D-资费 S-服务    
  - type: mobile #手机成员
    netTypeCode: '50'
    min: 1
    max: 3
    aopHidePackages: 1
    bundleList: #新装纳入成员
      - bundleId: '31000004'
        bundleName: '智慧沃家组合套餐（商用）-4G全国套餐-76元套餐（新）'
        allowAdd: 1 # 1：允许  0 ：不允许 融合成员纳入
        allowNew: 1 # 1：允许  0 ：不允许 融合成员新装
        products:
        -
          productId: '89950166'
          productMode: '00'
          packages: # 商品固定带的包元素组合
            - packageId: '51716939'
              elementId: '5688200'
              elementType: D # D-资费 S-服务
            - packageId: '59999793'
              elementId: '50000'
              elementType: S # D-资费 S-服务
        
      #- bundleId: '10000494'
      #  bundleName: '4G成员套内产品'
      #  allowAdd: 1 # 1：允许  0 ：不允许 融合成员纳入
      #  allowNew: 0 # 1：允许  0 ：不允许 融合成员新装
      #  products:
      #  -
      #    productId: '89002922'
      #    productMode: '00'
      #    packages: # 商品固定带的包元素组合
      #      - packageId: '89002922'
      #        elementId: '89002922'
      #        elementType: D # D-资费 S-服务
      #      - packageId: '51018052'
      #        elementId: '50004'
      #        elementType: S # D-资费 S-服务
  - type: broadband #宽带
    netTypeCode: '40'
    min: 1
    max: 2
    bundleList: #新装纳入
      - bundleId: '10000458'
        bundleName: '天津宽带50M包月80元'
        speedLevel: '50' #宽带必填
        allowAdd: 1 # 1：允许  0 ：不允许 融合成员纳入
        allowNew: 1 # 1：允许  0 ：不允许 融合成员新装
        products:
        -
          productId: '89003020'
          productMode: '00'
          packages: # 商品固定带的包元素组合
           - packageId: '51003570'
             elementId: '7110612'
             elementType: D # D-资费 S-服务
           #- packageId: '51003173'
           #  elementId: '40000'
           #  elementType: S # D-资费 S-服务
      
      - bundleId: '10000459'
        bundleName: '天津宽带50M一年600元'
        speedLevel: '50' #宽带必传
        allowAdd: 1 # 1：允许  0 ：不允许 融合成员纳入
        allowNew: 1 # 1：允许  0 ：不允许 融合成员新装
        products:
        -
          productId: '89003020'
          productMode: '00'
          packages: # 商品固定带的包元素组合
           - packageId: '51003570'
             elementId: '7113010'
             elementType: D # D-资费 S-服务
      - bundleId: '30001110'
        bundleName: '天津宽带200M基本套餐（2019年）-套餐加装30元'
        speedLevel: '200' #宽带必传
        allowAdd: 1 # 1：允许  0 ：不允许 融合成员纳入
        allowNew: 1 # 1：允许  0 ：不允许 融合成员新装
        products:
        -
          productId: '90691995'
          productMode: '00'
          packages: # 商品固定带的包元素组合
           - packageId: '52344380'
             elementId: '61738134'
             elementType: D # D-资费 S-服务
           - packageId: '51003173'
             elementId: '40000'
             elementType: S # D-资费 S-服务
  - type: fixed #固话
    netTypeCode: '31'
    min: 1
    max: 1
    bundleList: #新装纳入
      - bundleId: '31000001'
        bundleName: '天津公众固话18元月租标准产品'
        allowAdd: 1 # 1：允许  0 ：不允许 融合成员纳入
        allowNew: 1 # 1：允许  0 ：不允许 融合成员新装
        products:
        -
          productId: '89003070'
          productMode: '00'
          packages: # 商品固定带的包元素组合
           - packageId: '51019291'
             elementId: '30000'
             elementType: S # D-资费 S-服务
           - packageId: '51003637'
             elementId: '7010028'
             elementType: D # D-资费 S-服务
  - type: IPTV #IPTV
    netTypeCode: '49'
    min: 0
    max: 1
    bundleList: #新装纳入
      - bundleId: '30001004'
        bundleName: '天津高清IPTV-10元/月'
        allowAdd: 1 # 1：允许  0 ：不允许 融合成员纳入
        allowNew: 1 # 1：允许  0 ：不允许 融合成员新装
        products:
        -
          productId: '89003047'
          productMode: '00'
          packages: # 商品固定带的包元素组合
           - packageId: '51003607'
             elementId: '4013111'
             elementType: S # D-资费 S-服务
           - packageId: '51003607'
             elementId: '7129510'
             elementType: D # D-资费 S-服务
      #- bundleId: '30000314'
      #  bundleName: '天津高清IPTV-20元/月'
      #  allowAdd: 1 # 1：允许  0 ：不允许 融合成员纳入
      #  allowNew: 1 # 1：允许  0 ：不允许 融合成员新装
      #  products:
      #  -
      #    productId: '89003047'
      #    productMode: '00'
      #    packages: # 商品固定带的包元素组合
      #     - packageId: '51003607'
      #       elementId: '4013111'
      #       elementType: S # D-资费 S-服务
      #     - packageId: '51003607'
      #       elementId: '7129701'
      #       elementType: D # D-资费 S-服务
