sysCode: CBS # 目前都是 CBS
useCase: #菜单显示
  - wohome
  - wosale
mixNetType: '8806' # 目标融合类型，调用aop融合成员预提交接口用到
xxProductId: '30000270' # 行销商品标识，同意向单中的产品标识
xxProductName: '[公众]全家红48元月租版(2019)' # 前台显示商品详细描述的文字
cbProductId: '90524650' # 提交集团接口 cb/aop 的产品标识
allowFromProducts: #cbss融合可以转此融合
  - '90524662'
  - '90377902'
members: # 配置包括主虚拟号在内的各类成员
  - type: CP # 成员英文类别，行销专用
    netTypeCode: 'CP' # 虚拟成员
    min: 1
    max: 1
    bundleList: #新装纳入
      - bundleId: '30000270'
        bundleName: '[公众]全家红48元月租版(2019)'
        allowAdd: 1 # 1：允许  0 ：不允许 融合成员纳入
        allowNew: 1 # 1：允许  0 ：不允许 融合成员新装
        products:
        -
          productId: '90524650'
          productMode: '00'
          packages: # 商品固定带的包元素组合
           - packageId: '52174897'
             elementId: '8662217'
             elementType: D # D-资费 S-服务
           - packageId: '52175059'
             elementId: '41302080'
             elementType: D # D-资费 S-服务
           - packageId: '51002268'
             elementId: '50000'
             elementType:  S # D-资费 S-服务
  - type: mobile #手机成员
    netTypeCode: '50'
    min: 1
    max: 2
    aopHidePackages: 1
    bundleList: #新装纳入成员
      - bundleId: '30000256'
        bundleName: '智慧沃家手机成员'
        allowAdd: 1 # 1：允许  0 ：不允许 融合成员纳入
        allowNew: 1 # 1：允许  0 ：不允许 融合成员新装
        products:
          -
            productId: '90311178'
            productMode: '00'
            packages: # 商品固定带的包元素组合
            # - packageId: '59999793'
            #   elementId: '50103'
            #   elementType: S # D-资费 S-服务
             - packageId: '59999793'
               elementId: '50103'
               elementType: S # D-资费 S-服务
          -
            productId: '90393594'
            productMode: '01'
            close2g: 1
            packages: # 商品固定带的包元素组合
             - packageId: '52035855'
               elementId: '50315'
               elementType: S # D-资费 S-服务

  - type: broadband #宽带
    netTypeCode: '40'
    min: 1
    max: 2
    bundleList: #新装纳入
      - bundleId: '30000271'
        bundleName: '天津宽带100M-30元/月'
        speedLevel: '100' #宽带必填
        allowAdd: 1 # 1：允许  0 ：不允许 融合成员纳入
        allowNew: 1 # 1：允许  0 ：不允许 融合成员新装
        products:
        -
          productId: '90422862'
          productMode: '00'
          packages: # 商品固定带的包元素组合
           - packageId: '52070927'
             elementId: '8523834'
             elementType: D # D-资费 S-服务
           - packageId: '51003173'
             elementId: '40000'
             elementType: S # D-资费 S-服务
        -
          productId: '90430580'
          productMode: '01'
          packages: # 商品固定带的包元素组合
           - packageId: '52076643'
             elementId: '8540310'
             elementType: D # D-资费 S-服务

  - type: fixed #固话
    netTypeCode: '31'
    min: 0
    max: 1
    bundleList: #新装纳入
      - bundleId: '30000255'
        bundleName: '智慧沃家固话成员'
        allowAdd: 1 # 1：允许  0 ：不允许 融合成员纳入
        allowNew: 1 # 1：允许  0 ：不允许 融合成员新装
        products:
        -
          productId: '90359749'
          productMode: '00'
          packages: # 商品固定带的包元素组合
           - packageId: '51019292'
             elementId: '30075'
             elementType: S # D-资费 S-服务
           - packageId: '51019292'
             elementId: '7000530'
             elementType: D # D-资费 S-服务
  - type: IPTV #IPTV
    netTypeCode: '49'
    min: 0
    max: 1
    bundleList: #新装纳入
      - bundleId: '30000314'
        bundleName: '天津高清IPTV-20元/月'
        allowAdd: 1 # 1：允许  0 ：不允许 融合成员纳入
        allowNew: 1 # 1：允许  0 ：不允许 融合成员新装
        products:
        -
          productId: '89003047'
          productMode: '00'
          packages: # 商品固定带的包元素组合
           - packageId: '51003607'
             elementId: '4013111'
             elementType: S # D-资费 S-服务
           - packageId: '51003607'
             elementId: '7129701'
             elementType: D # D-资费 S-服务
