sysCode: CBS # 目前都是 CBS
useCase: #菜单显示
  - wohome
  - wosale
mixNetType: '8930' # 目标融合类型，调用aop融合成员预提交接口用到
xxProductId: '30000440' # 行销商品标识，同意向单中的产品标识
xxProductName: '599元冰激凌尊享红融合' # 前台显示商品详细描述的文字
cbProductId: '90524719' # 提交集团接口 cb/aop 的产品标识
allowFromProducts: #cbss融合可以转此融合
  - '90361012'
  - '90311214'
members: # 配置包括主虚拟号在内的各类成员
  - type: CP # 成员英文类别，行销专用
    netTypeCode: 'CP' # 虚拟成员
    min: 1
    max: 1
    bundleList: #新装纳入
      - bundleId: '30000440'
        bundleName: '599元冰激凌尊享红融合'
        allowAdd: 1 # 1：允许  0 ：不允许 融合成员纳入
        allowNew: 1 # 1：允许  0 ：不允许 融合成员新装
        products:
        -
          productId: '90524719'
          productMode: '00'
          packages: # 商品固定带的包元素组合
           - packageId: '51002268'
             elementId: '50000'
             elementType: S # D-资费 S-服务
           - packageId: '51018573'
             elementId: '7000100'
             elementType: D # D-资费 S-服务

  - type: mobile #手机成员
    netTypeCode: '50'
    min: 1
    max: 1
    aopHidePackages: 1
    bundleList: #新装纳入成员
      - bundleId: '30000446'
        bundleName: '冰激凌手机成员-599元'
        allowAdd: 0 # 1：允许  0 ：不允许 融合成员纳入
        allowNew: 1 # 1：允许  0 ：不允许 融合成员新装
        products:
          -
            productId: '90451651'
            productMode: '00'
            packages: # 商品固定带的包元素组合
            # - packageId: '59999793'
            #   elementId: '50103'
            #   elementType: S # D-资费 S-服务
             - packageId: '51858303'
               elementId: '50103'
               elementType: S # D-资费 S-服务
          -
            productId: '90393594'
            productMode: '01'
            close2g: 1
            packages: # 商品固定带的包元素组合
             - packageId: '52035855'
               elementId: '50315'
               elementType: S # D-资费 S-服务
          -
            productId: '90462864'
            productMode: '01'
            close2g: 1
            packages: # 商品固定带的包元素组合
             - packageId: '52109139'
               elementId: '8613373'
               elementType: D # D-资费 S-服务
        
      - bundleId: '30000448'
        bundleName: '冰激凌手机成员-599元'
        allowAdd: 1 # 1：允许  0 ：不允许 融合成员纳入
        allowNew: 0 # 1：允许  0 ：不允许 融合成员新装
        products:
          -
            productId: '90451651'
            productMode: '00'
            packages: # 商品固定带的包元素组合
            # - packageId: '59999793'
            #   elementId: '50103'
            #   elementType: S # D-资费 S-服务
             - packageId: '51858303'
               elementId: '50103'
               elementType: S # D-资费 S-服务
          -
            productId: '90393594'
            productMode: '01'
            close2g: 1
            packages: # 商品固定带的包元素组合
             - packageId: '52035855'
               elementId: '50315'
               elementType: S # D-资费 S-服务
        
  - type: broadband #宽带
    netTypeCode: '40'
    min: 1
    max: 2
    bundleList: #新装纳入
      - bundleId: '30000421'
        bundleName: '冰红卡宽带500M-0元/月'
        speedLevel: '500' #宽带必填
        allowAdd: 1 # 1：允许  0 ：不允许 融合成员纳入
        allowNew: 1 # 1：允许  0 ：不允许 融合成员新装
        products:
        -
          productId: '90524705'
          productMode: '00'
          packages: # 商品固定带的包元素组合
           - packageId: '52174967'
             elementId: '8661868'
             elementType: D # D-资费 S-服务
           - packageId: '51003173'
             elementId: '40000'
             elementType: S # D-资费 S-服务
        #-
        #  productId: '90430580'
        #  productMode: '01'
        #  packages: # 商品固定带的包元素组合
        #   - packageId: '52076643'
        #     elementId: '8540310'
        #     elementType: D # D-资费 S-服务
        #activities:
        #  - actPlanId: '90524786'
      - bundleId: '30001110'
        bundleName: '天津宽带200M基本套餐（2019年）-套餐加装30元'
        speedLevel: '200' #宽带必传
        allowAdd: 1 # 1：允许  0 ：不允许 融合成员纳入
        allowNew: 1 # 1：允许  0 ：不允许 融合成员新装
        products:
        -
          productId: '90691995'
          productMode: '00'
          packages: # 商品固定带的包元素组合
           - packageId: '52344380'
             elementId: '61738134'
             elementType: D # D-资费 S-服务
           - packageId: '51003173'
             elementId: '40000'
             elementType: S # D-资费 S-服务
  - type: fixed #固话
    netTypeCode: '31'
    min: 0
    max: 1
    bundleList: #新装纳入
      - bundleId: '30000405'
        bundleName: '冰红卡固话成员'
        allowAdd: 1 # 1：允许  0 ：不允许 融合成员纳入
        allowNew: 1 # 1：允许  0 ：不允许 融合成员新装
        products:
        -
          productId: '90524721'
          productMode: '00'
          packages: # 商品固定带的包元素组合
           - packageId: '51019292'
             elementId: '30075'
             elementType: S # D-资费 S-服务
           - packageId: '51019292'
             elementId: '7000530'
             elementType: D # D-资费 S-服务
           - packageId: '52174999'
             elementId: '8663119'
             elementType: D # D-资费 S-服务
  - type: IPTV #IPTV
    netTypeCode: '49'
    min: 0
    max: 1
    bundleList: #新装纳入
      - bundleId: '30001004'
        bundleName: '天津高清IPTV-10元/月'
        allowAdd: 1 # 1：允许  0 ：不允许 融合成员纳入
        allowNew: 1 # 1：允许  0 ：不允许 融合成员新装
        products:
        -
          productId: '89003047'
          productMode: '00'
          packages: # 商品固定带的包元素组合
           - packageId: '51003607'
             elementId: '4013111'
             elementType: S # D-资费 S-服务
           - packageId: '51003607'
             elementId: '7129510'
             elementType: D # D-资费 S-服务
      #- bundleId: '30000314'
      #  bundleName: '天津高清IPTV-20元/月'
      #  allowAdd: 1 # 1：允许  0 ：不允许 融合成员纳入
      #  allowNew: 1 # 1：允许  0 ：不允许 融合成员新装
      #  products:
      #  -
      #    productId: '89003047'
      #    productMode: '00'
      #    packages: # 商品固定带的包元素组合
      #     - packageId: '51003607'
      #       elementId: '4013111'
      #       elementType: S # D-资费 S-服务
      #     - packageId: '51003607'
      #       elementId: '7129701'
      #       elementType: D # D-资费 S-服务